// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PromVesClient;

#nullable disable

namespace PromVesClient.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260810054653_AddWagon")]
    partial class AddWagon
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PromVesClient.Models.Receipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeWeighng")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("PromVesClient.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PromVesClient.Models.Wagon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TareWeight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Wagons");
                });

            modelBuilder.Entity("PromVesClient.Models.Weighing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("DifferenceCarts")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DifferenceSides")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FirstCart")
                        .HasColumnType("numeric");

                    b.Property<decimal>("GrossWeight")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("InvoiceDataTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("text");

                    b.Property<decimal?>("InvoiceWeighing")
                        .HasColumnType("numeric");

                    b.Property<decimal>("L1")
                        .HasColumnType("numeric");

                    b.Property<decimal>("L2")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LeftSide")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LoadCapacity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LoadDeviation")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NetWeight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("R1")
                        .HasColumnType("numeric");

                    b.Property<decimal>("R2")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("RightSide")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SecondCart")
                        .HasColumnType("numeric");

                    b.Property<string>("Shipper")
                        .HasColumnType("text");

                    b.Property<decimal>("TareWeight")
                        .HasColumnType("numeric");

                    b.Property<string>("TypeWeighing")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VagonNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Сargo")
                        .HasColumnType("text");

                    b.Property<string>("Сonsignee")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptId");

                    b.ToTable("Weighings");
                });

            modelBuilder.Entity("PromVesClient.Models.Weighing", b =>
                {
                    b.HasOne("PromVesClient.Models.Receipt", "Receipt")
                        .WithMany("Weighings")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("PromVesClient.Models.Receipt", b =>
                {
                    b.Navigation("Weighings");
                });
#pragma warning restore 612, 618
        }
    }
}
