// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PromVesClient;

#nullable disable

namespace PromVesClient.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260804094126_Inithial")]
    partial class Inithial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PromVesClient.Models.Receipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeWeighng")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("PromVesClient.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PromVesClient.Models.Weighing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("DifferenceCarts")
                        .HasColumnType("double precision");

                    b.Property<double>("DifferenceSides")
                        .HasColumnType("double precision");

                    b.Property<double>("FirstCart")
                        .HasColumnType("double precision");

                    b.Property<double>("GrossWeight")
                        .HasColumnType("double precision");

                    b.Property<double>("LeftSide")
                        .HasColumnType("double precision");

                    b.Property<double>("LoadCapacity")
                        .HasColumnType("double precision");

                    b.Property<double>("LoadDeviation")
                        .HasColumnType("double precision");

                    b.Property<double>("NetWeight")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid");

                    b.Property<double>("RightSide")
                        .HasColumnType("double precision");

                    b.Property<double>("SecondCart")
                        .HasColumnType("double precision");

                    b.Property<double>("TareWeight")
                        .HasColumnType("double precision");

                    b.Property<string>("TypeWeighing")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VagonNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptId");

                    b.ToTable("Weighings");
                });

            modelBuilder.Entity("PromVesClient.Models.Weighing", b =>
                {
                    b.HasOne("PromVesClient.Models.Receipt", "Receipt")
                        .WithMany("Weighings")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("PromVesClient.Models.Receipt", b =>
                {
                    b.Navigation("Weighings");
                });
#pragma warning restore 612, 618
        }
    }
}
